language: node_js
cache:
  directories:
    - node_modules
    - .cache
notifications:
  email: false
node_js:
  - "node"
before_install: ./scripts/travis/before_install.sh
after_success: ./scripts/travis/after_success.sh
script:
  - npm run bootstrap
  - (cd examples/test-cra && npm install)
  - npm run lint
  - npm run test -- --coverage
  - npm run coverage
git:
  depth: 1
