language: node_js
node_js:
- '6'
install:
- npm install -g coveralls
- npm install
script:
- npm test
sudo: false
deploy:
  provider: npm
  email: james.baxley@newspring.cc
  api_key:
    secure: b9yU50a9kOq8lgVFe3gtYzOAGjbHHNLHoJ1F+d2MLa9P4qLYOz6bQ6WL/d9vDNjAM1RP5scQtbYFP6WJz2CqZ30vVVcXGG651rA+5xnz2VQtNFfVtOO76nIlVPaZlluPpyX5DfuRrvLKMxOGKJ16q1G5wZzXAgmHF74vTGNO90m3fpw4edotiO9LOOQ3fMuNl3zQBDuxDGVm9zZ5JmN2T7LNifitY8R1H6YkJD/+kF1jrHjGjV7wnc4YnQd4uXIzR1L0SjmOmF3uLHZekSYVS9+YL4B2i0W9Og2tWmgH488FsnOpRL16IaLCZ9+GTBZlNP5QwB+CAt3bl6mki+bTJ2lrEQIfMyhhr4TKP3IXqD3dK9MSDv2EEreWuWiwWEeobY5mjvBaT6McDwM/JTqXHk4OXNcolaxyWPO/+V2SqWakoudcPcu0RCfSE+CKwLy8mJmZskzNZHyLWiZ4AOkrGZl6a2wqyUvvwMBjtw3n+ptOZvFGy9OVVugCnGhvnlwIlq6L2WHN0780DOndJSGJ9KKYosGaSNXyrhm+1JRf7r/iEmtuEpWH6D0CzC4y7+80w/T1xajHTV6DL8r7h4VWuFRod8JsMSDcgpeDT9Ofv2+IMZhqY78y9oE/24pgU7nhRapAZ60chvcQWvs0sAV969UyIBs37q784w455KcRaWk=
  on:
    tags: true
    repo: NewSpring/react-storybook-addon-backgrounds
